kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: wordpress
  labels:
    tier: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mysql/"