kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-pv
  namespace: wordpress
  labels:
    tier: frontend
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/wordpress/"